enum Preferences {
  boolHasRatedTrip,
  boolActiveRoute,
  stringLocalRequestStartAddress,
  stringLocalRequestEndAddress,
  intCurrentScreen,
  intLoggingAuth,
  intLoggingUsers,
  intLoggingRoutings,
  intLoggingRequests,
  intLoggingChecks,
  intLoggingBookings,
  intLoggingAutocomplete,
  intLoggingCoordinats,
  intLoggingProviderUser,
}
