// Mocks generated by Mockito 5.0.7 from annotations
// in Sublin/test/debug/secreens/user_my_lib_screen_debug.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:Sublin/services/provider_user_service.dart' as _i2;
import 'package:Sublin/utils/get_list_of_address_info_from_list_of_provider_users_and_user.dart'
    as _i3;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [ProviderUserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProviderUserService extends _i1.Mock
    implements _i2.ProviderUserService {
  MockProviderUserService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [AddressInfoProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddressInfoProvider extends _i1.Mock
    implements _i3.AddressInfoProvider {
  MockAddressInfoProvider() {
    _i1.throwOnMissingStub(this);
  }
}
